name: Pull Request
on:
  pull_request:
    branches:
    - main
jobs:
  check-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            node-version: 12
            registry-url: https://npm.pkg.github.com/
            scope: "@rollcakejs"
      - name: Installing jest globally
        run: |
          npm install -g jest
      - name: Installing dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@rollcakejs:registry=https://npm.pkg.github.com/" >> .npmrc
          npm install
      - name: Check test
        run: |
          npm run test